const MINECRAFT_ITEMS = [
  { id: 0, name: "Air", mcId: "minecraft:air" },
  { id: 1, name: "Stone", mcId: "minecraft:stone" },
  { id: "1:1", name: "Granite", mcId: "minecraft:stone" },
  { id: "1:2", name: "Polished Granite", mcId: "minecraft:stone" },
  { id: "1:3", name: "Diorite", mcId: "minecraft:stone" },
  { id: "1:4", name: "Polished Diorite", mcId: "minecraft:stone" },
  { id: "1:5", name: "Andesite", mcId: "minecraft:stone" },
  { id: "1:6", name: "Polished Andesite", mcId: "minecraft:stone" },
  { id: 2, name: "Grass", mcId: "minecraft:grass" },
  { id: 3, name: "Dirt", mcId: "minecraft:dirt" },
  { id: "3:1", name: "Coarse Dirt", mcId: "minecraft:dirt" },
  { id: "3:2", name: "Podzol", mcId: "minecraft:dirt" },
  { id: 4, name: "Cobblestone", mcId: "minecraft:cobblestone" },
  { id: 5, name: "Oak Wood Plank", mcId: "minecraft:planks" },
  { id: "5:1", name: "Spruce Wood Plank", mcId: "minecraft:planks" },
  { id: "5:2", name: "Birch Wood Plank", mcId: "minecraft:planks" },
  { id: "5:3", name: "Jungle Wood Plank", mcId: "minecraft:planks" },
  { id: "5:4", name: "Acacia Wood Plank", mcId: "minecraft:planks" },
  { id: "5:5", name: "Dark Oak Wood Plank", mcId: "minecraft:planks" },
  { id: 6, name: "Oak Sapling", mcId: "minecraft:sapling" },
  { id: "6:1", name: "Spruce Sapling", mcId: "minecraft:sapling" },
  { id: "6:2", name: "Birch Sapling", mcId: "minecraft:sapling" },
  { id: "6:3", name: "Jungle Sapling", mcId: "minecraft:sapling" },
  { id: "6:4", name: "Acacia Sapling", mcId: "minecraft:sapling" },
  { id: "6:5", name: "Dark Oak Sapling", mcId: "minecraft:sapling" },
  { id: 7, name: "Bedrock", mcId: "minecraft:bedrock" },
  { id: 8, name: "Flowing Water", mcId: "minecraft:flowing_water" },
  { id: 9, name: "Still Water", mcId: "minecraft:water" },
  { id: 10, name: "Flowing Lava", mcId: "minecraft:flowing_lava" },
  { id: 11, name: "Still Lava", mcId: "minecraft:lava" },
  { id: 12, name: "Sand", mcId: "minecraft:sand" },
  { id: "12:1", name: "Red Sand", mcId: "minecraft:sand" },
  { id: 13, name: "Gravel", mcId: "minecraft:gravel" },
  { id: 14, name: "Gold Ore", mcId: "minecraft:gold_ore" },
  { id: 15, name: "Iron Ore", mcId: "minecraft:iron_ore" },
  { id: 16, name: "Coal Ore", mcId: "minecraft:coal_ore" },
  { id: 17, name: "Oak Wood", mcId: "minecraft:log" },
  { id: "17:1", name: "Spruce Wood", mcId: "minecraft:log" },
  { id: "17:2", name: "Birch Wood", mcId: "minecraft:log" },
  { id: "17:3", name: "Jungle Wood", mcId: "minecraft:log" },
  { id: 18, name: "Oak Leaves", mcId: "minecraft:leaves" },
  { id: "18:1", name: "Spruce Leaves", mcId: "minecraft:leaves" },
  { id: "18:2", name: "Birch Leaves", mcId: "minecraft:leaves" },
  { id: "18:3", name: "Jungle Leaves", mcId: "minecraft:leaves" },
  { id: 19, name: "Sponge", mcId: "minecraft:sponge" },
  { id: "19:1", name: "Wet Sponge", mcId: "minecraft:sponge" },
  { id: 20, name: "Glass", mcId: "minecraft:glass" },
  { id: 21, name: "Lapis Lazuli Ore", mcId: "minecraft:lapis_ore" },
  { id: 22, name: "Lapis Lazuli Block", mcId: "minecraft:lapis_block" },
  { id: 23, name: "Dispenser", mcId: "minecraft:dispenser" },
  { id: 24, name: "Sandstone", mcId: "minecraft:sandstone" },
  { id: "24:1", name: "Chiseled Sandstone", mcId: "minecraft:sandstone" },
  { id: "24:2", name: "Smooth Sandstone", mcId: "minecraft:sandstone" },
  { id: 25, name: "Note Block", mcId: "minecraft:noteblock" },
  { id: 26, name: "Bed", mcId: "minecraft:bed" },
  { id: 27, name: "Powered Rail", mcId: "minecraft:golden_rail" },
  { id: 28, name: "Detector Rail", mcId: "minecraft:detector_rail" },
  { id: 29, name: "Sticky Piston", mcId: "minecraft:sticky_piston" },
  { id: 30, name: "Cobweb", mcId: "minecraft:web" },
  { id: 31, name: "Dead Shrub", mcId: "minecraft:tallgrass" },
  { id: "31:1", name: "Grass", mcId: "minecraft:tallgrass" },
  { id: "31:2", name: "Fern", mcId: "minecraft:tallgrass" },
  { id: 32, name: "Dead Shrub", mcId: "minecraft:deadbush" },
  { id: 33, name: "Piston", mcId: "minecraft:piston" },
  { id: 34, name: "Piston Head", mcId: "minecraft:piston_head" },
  { id: 35, name: "White Wool", mcId: "minecraft:wool" },
  { id: "35:1", name: "Orange Wool", mcId: "minecraft:wool" },
  { id: "35:2", name: "Magenta Wool", mcId: "minecraft:wool" },
  { id: "35:3", name: "Light Blue Wool", mcId: "minecraft:wool" },
  { id: "35:4", name: "Yellow Wool", mcId: "minecraft:wool" },
  { id: "35:5", name: "Lime Wool", mcId: "minecraft:wool" },
  { id: "35:6", name: "Pink Wool", mcId: "minecraft:wool" },
  { id: "35:7", name: "Gray Wool", mcId: "minecraft:wool" },
  { id: "35:8", name: "Light Gray Wool", mcId: "minecraft:wool" },
  { id: "35:9", name: "Cyan Wool", mcId: "minecraft:wool" },
  { id: "35:10", name: "Purple Wool", mcId: "minecraft:wool" },
  { id: "35:11", name: "Blue Wool", mcId: "minecraft:wool" },
  { id: "35:12", name: "Brown Wool", mcId: "minecraft:wool" },
  { id: "35:13", name: "Green Wool", mcId: "minecraft:wool" },
  { id: "35:14", name: "Red Wool", mcId: "minecraft:wool" },
  { id: "35:15", name: "Black Wool", mcId: "minecraft:wool" },
  { id: 37, name: "Dandelion", mcId: "minecraft:yellow_flower" },
  { id: 38, name: "Poppy", mcId: "minecraft:red_flower" },
  { id: "38:1", name: "Blue Orchid", mcId: "minecraft:red_flower" },
  { id: "38:2", name: "Allium", mcId: "minecraft:red_flower" },
  { id: "38:3", name: "Azure Bluet", mcId: "minecraft:red_flower" },
  { id: "38:4", name: "Red Tulip", mcId: "minecraft:red_flower" },
  { id: "38:5", name: "Orange Tulip", mcId: "minecraft:red_flower" },
  { id: "38:6", name: "White Tulip", mcId: "minecraft:red_flower" },
  { id: "38:7", name: "Pink Tulip", mcId: "minecraft:red_flower" },
  { id: "38:8", name: "Oxeye Daisy", mcId: "minecraft:red_flower" },
  { id: 39, name: "Brown Mushroom", mcId: "minecraft:brown_mushroom" },
  { id: 40, name: "Red Mushroom", mcId: "minecraft:red_mushroom" },
  { id: 41, name: "Gold Block", mcId: "minecraft:gold_block" },
  { id: 42, name: "Iron Block", mcId: "minecraft:iron_block" },
  { id: 43, name: "Double Stone Slab", mcId: "minecraft:double_stone_slab" },
  { id: "43:1", name: "Double Sandstone Slab", mcId: "minecraft:double_stone_slab" },
  { id: "43:2", name: "Double Wooden Slab", mcId: "minecraft:double_stone_slab" },
  { id: "43:3", name: "Double Cobblestone Slab", mcId: "minecraft:double_stone_slab" },
  { id: "43:4", name: "Double Brick Slab", mcId: "minecraft:double_stone_slab" },
  { id: "43:5", name: "Double Stone Brick Slab", mcId: "minecraft:double_stone_slab" },
  { id: "43:6", name: "Double Nether Brick Slab", mcId: "minecraft:double_stone_slab" },
  { id: "43:7", name: "Double Quartz Slab", mcId: "minecraft:double_stone_slab" },
  { id: 44, name: "Stone Slab", mcId: "minecraft:stone_slab" },
  { id: "44:1", name: "Sandstone Slab", mcId: "minecraft:stone_slab" },
  { id: "44:2", name: "Wooden Slab", mcId: "minecraft:stone_slab" },
  { id: "44:3", name: "Cobblestone Slab", mcId: "minecraft:stone_slab" },
  { id: "44:4", name: "Brick Slab", mcId: "minecraft:stone_slab" },
  { id: "44:5", name: "Stone Brick Slab", mcId: "minecraft:stone_slab" },
  { id: "44:6", name: "Nether Brick Slab", mcId: "minecraft:stone_slab" },
  { id: "44:7", name: "Quartz Slab", mcId: "minecraft:stone_slab" },
  { id: 45, name: "Bricks", mcId: "minecraft:brick_block" },
  { id: 46, name: "TNT", mcId: "minecraft:tnt" },
  { id: 47, name: "Bookshelf", mcId: "minecraft:bookshelf" },
  { id: 48, name: "Moss Stone", mcId: "minecraft:mossy_cobblestone" },
  { id: 49, name: "Obsidian", mcId: "minecraft:obsidian" },
  { id: 50, name: "Torch", mcId: "minecraft:torch" },
  { id: 51, name: "Fire", mcId: "minecraft:fire" },
  { id: 52, name: "Monster Spawner", mcId: "minecraft:mob_spawner" },
  { id: 53, name: "Oak Wood Stairs", mcId: "minecraft:oak_stairs" },
  { id: 54, name: "Chest", mcId: "minecraft:chest" },
  { id: 55, name: "Redstone Wire", mcId: "minecraft:redstone_wire" },
  { id: 56, name: "Diamond Ore", mcId: "minecraft:diamond_ore" },
  { id: 57, name: "Diamond Block", mcId: "minecraft:diamond_block" },
  { id: 58, name: "Crafting Table", mcId: "minecraft:crafting_table" },
  { id: 59, name: "Wheat Crops", mcId: "minecraft:wheat" },
  { id: 60, name: "Farmland", mcId: "minecraft:farmland" },
  { id: 61, name: "Furnace", mcId: "minecraft:furnace" },
  { id: 62, name: "Burning Furnace", mcId: "minecraft:lit_furnace" },
  { id: 63, name: "Standing Sign Block", mcId: "minecraft:standing_sign" },
  { id: 64, name: "Wooden Door Block", mcId: "minecraft:wooden_door" },
  { id: 65, name: "Ladder", mcId: "minecraft:ladder" },
  { id: 66, name: "Rail", mcId: "minecraft:rail" },
  { id: 67, name: "Cobblestone Stairs", mcId: "minecraft:stone_stairs" },
  { id: 68, name: "Wall-mounted Sign Block", mcId: "minecraft:wall_sign" },
  { id: 69, name: "Lever", mcId: "minecraft:lever" },
  { id: 70, name: "Stone Pressure Plate", mcId: "minecraft:stone_pressure_plate" },
  { id: 71, name: "Iron Door Block", mcId: "minecraft:iron_door" },
  { id: 72, name: "Wooden Pressure Plate", mcId: "minecraft:wooden_pressure_plate" },
  { id: 73, name: "Redstone Ore", mcId: "minecraft:redstone_ore" },
  { id: 74, name: "Glowing Redstone Ore", mcId: "minecraft:lit_redstone_ore" },
  { id: 75, name: "Redstone Torch", mcId: "off) (minecraft:unlit_redstone_torch" },
  { id: 76, name: "Redstone Torch", mcId: "on) (minecraft:redstone_torch" },
  { id: 77, name: "Stone Button", mcId: "minecraft:stone_button" },
  { id: 78, name: "Snow", mcId: "minecraft:snow_layer" },
  { id: 79, name: "Ice", mcId: "minecraft:ice" },
  { id: 80, name: "Snow Block", mcId: "minecraft:snow" },
  { id: 81, name: "Cactus", mcId: "minecraft:cactus" },
  { id: 82, name: "Clay", mcId: "minecraft:clay" },
  { id: 83, name: "Sugar Canes", mcId: "minecraft:reeds" },
  { id: 84, name: "Jukebox", mcId: "minecraft:jukebox" },
  { id: 85, name: "Oak Fence", mcId: "minecraft:fence" },
  { id: 86, name: "Pumpkin", mcId: "minecraft:pumpkin" },
  { id: 87, name: "Netherrack", mcId: "minecraft:netherrack" },
  { id: 88, name: "Soul Sand", mcId: "minecraft:soul_sand" },
  { id: 89, name: "Glowstone", mcId: "minecraft:glowstone" },
  { id: 90, name: "Nether Portal", mcId: "minecraft:portal" },
  { id: 91, name: "Jack o’Lantern", mcId: "minecraft:lit_pumpkin" },
  { id: 92, name: "Cake Block", mcId: "minecraft:cake" },
  { id: 93, name: "Redstone Repeater Block", mcId: "off) (minecraft:unpowered_repeater" },
  { id: 94, name: "Redstone Repeater Block", mcId: "on) (minecraft:powered_repeater" },
  { id: 95, name: "White Stained Glass", mcId: "minecraft:stained_glass" },
  { id: "95:1", name: "Orange Stained Glass", mcId: "minecraft:stained_glass" },
  { id: "95:2", name: "Magenta Stained Glass", mcId: "minecraft:stained_glass" },
  { id: "95:3", name: "Light Blue Stained Glass", mcId: "minecraft:stained_glass" },
  { id: "95:4", name: "Yellow Stained Glass", mcId: "minecraft:stained_glass" },
  { id: "95:5", name: "Lime Stained Glass", mcId: "minecraft:stained_glass" },
  { id: "95:6", name: "Pink Stained Glass", mcId: "minecraft:stained_glass" },
  { id: "95:7", name: "Gray Stained Glass", mcId: "minecraft:stained_glass" },
  { id: "95:8", name: "Light Gray Stained Glass", mcId: "minecraft:stained_glass" },
  { id: "95:9", name: "Cyan Stained Glass", mcId: "minecraft:stained_glass" },
  { id: "95:10", name: "Purple Stained Glass", mcId: "minecraft:stained_glass" },
  { id: "95:11", name: "Blue Stained Glass", mcId: "minecraft:stained_glass" },
  { id: "95:12", name: "Brown Stained Glass", mcId: "minecraft:stained_glass" },
  { id: "95:13", name: "Green Stained Glass", mcId: "minecraft:stained_glass" },
  { id: "95:14", name: "Red Stained Glass", mcId: "minecraft:stained_glass" },
  { id: "95:15", name: "Black Stained Glass", mcId: "minecraft:stained_glass" },
  { id: 96, name: "Wooden Trapdoor", mcId: "minecraft:trapdoor" },
  { id: 97, name: "Stone Monster Egg", mcId: "minecraft:monster_egg" },
  { id: "97:1", name: "Cobblestone Monster Egg", mcId: "minecraft:monster_egg" },
  { id: "97:2", name: "Stone Brick Monster Egg", mcId: "minecraft:monster_egg" },
  { id: "97:3", name: "Mossy Stone Brick Monster Egg", mcId: "minecraft:monster_egg" },
  { id: "97:4", name: "Cracked Stone Brick Monster Egg", mcId: "minecraft:monster_egg" },
  { id: "97:5", name: "Chiseled Stone Brick Monster Egg", mcId: "minecraft:monster_egg" },
  { id: 98, name: "Stone Bricks", mcId: "minecraft:stonebrick" },
  { id: "98:1", name: "Mossy Stone Bricks", mcId: "minecraft:stonebrick" },
  { id: "98:2", name: "Cracked Stone Bricks", mcId: "minecraft:stonebrick" },
  { id: "98:3", name: "Chiseled Stone Bricks", mcId: "minecraft:stonebrick" },
  { id: 99, name: "Red Mushroom Cap", mcId: "minecraft:stonebrick" },
  { id: 100, name: "Brown Mushroom Cap", mcId: "minecraft:stonebrick" },
  { id: 101, name: "Iron Bars", mcId: "minecraft:iron_bars" },
  { id: 102, name: "Glass Pane", mcId: "minecraft:glass_pane" },
  { id: 103, name: "Melon Block", mcId: "minecraft:melon_block" },
  { id: 104, name: "Pumpkin Stem", mcId: "minecraft:pumpkin_stem" },
  { id: 105, name: "Melon Stem", mcId: "minecraft:melon_stem" },
  { id: 106, name: "Vines", mcId: "minecraft:vine" },
  { id: 107, name: "Oak Fence Gate", mcId: "minecraft:fence_gate" },
  { id: 108, name: "Brick Stairs", mcId: "minecraft:brick_stairs" },
  { id: 109, name: "Stone Brick Stairs", mcId: "minecraft:stone_brick_stairs" },
  { id: 110, name: "Mycelium", mcId: "minecraft:mycelium" },
  { id: 111, name: "Lily Pad", mcId: "minecraft:waterlily" },
  { id: 112, name: "Nether Brick", mcId: "minecraft:nether_brick" },
  { id: 113, name: "Nether Brick Fence", mcId: "minecraft:nether_brick_fence" },
  { id: 114, name: "Nether Brick Stairs", mcId: "minecraft:nether_brick_stairs" },
  { id: 115, name: "Nether Wart", mcId: "minecraft:nether_wart" },
  { id: 116, name: "Enchantment Table", mcId: "minecraft:enchanting_table" },
  { id: 117, name: "Brewing Stand", mcId: "minecraft:brewing_stand" },
  { id: 118, name: "Cauldron", mcId: "minecraft:cauldron" },
  { id: 119, name: "End Portal", mcId: "minecraft:end_portal" },
  { id: 120, name: "End Portal Frame", mcId: "minecraft:end_portal_frame" },
  { id: 121, name: "End Stone", mcId: "minecraft:end_stone" },
  { id: 122, name: "Dragon Egg", mcId: "minecraft:dragon_egg" },
  { id: 123, name: "Redstone Lamp", mcId: "inactive) (minecraft:redstone_lamp" },
  { id: 124, name: "Redstone Lamp", mcId: "active) (minecraft:lit_redstone_lamp" },
  { id: 125, name: "Double Oak Wood Slab", mcId: "minecraft:double_wooden_slab" },
  { id: "125:1", name: "Double Spruce Wood Slab", mcId: "minecraft:double_wooden_slab" },
  { id: "125:2", name: "Double Birch Wood Slab", mcId: "minecraft:double_wooden_slab" },
  { id: "125:3", name: "Double Jungle Wood Slab", mcId: "minecraft:double_wooden_slab" },
  { id: "125:4", name: "Double Acacia Wood Slab", mcId: "minecraft:double_wooden_slab" },
  { id: "125:5", name: "Double Dark Oak Wood Slab", mcId: "minecraft:double_wooden_slab" },
  { id: 126, name: "Oak Wood Slab", mcId: "minecraft:wooden_slab" },
  { id: "126:1", name: "Spruce Wood Slab", mcId: "minecraft:wooden_slab" },
  { id: "126:2", name: "Birch Wood Slab", mcId: "minecraft:wooden_slab" },
  { id: "126:3", name: "Jungle Wood Slab", mcId: "minecraft:wooden_slab" },
  { id: "126:4", name: "Acacia Wood Slab", mcId: "minecraft:wooden_slab" },
  { id: "126:5", name: "Dark Oak Wood Slab", mcId: "minecraft:wooden_slab" },
  { id: 127, name: "Cocoa", mcId: "minecraft:cocoa" },
  { id: 128, name: "Sandstone Stairs", mcId: "minecraft:sandstone_stairs" },
  { id: 129, name: "Emerald Ore", mcId: "minecraft:emerald_ore" },
  { id: 130, name: "Ender Chest", mcId: "minecraft:ender_chest" },
  { id: 131, name: "Tripwire Hook", mcId: "minecraft:tripwire_hook" },
  { id: 132, name: "Tripwire", mcId: "minecraft:tripwire_hook" },
  { id: 133, name: "Emerald Block", mcId: "minecraft:emerald_block" },
  { id: 134, name: "Spruce Wood Stairs", mcId: "minecraft:spruce_stairs" },
  { id: 135, name: "Birch Wood Stairs", mcId: "minecraft:birch_stairs" },
  { id: 136, name: "Jungle Wood Stairs", mcId: "minecraft:jungle_stairs" },
  { id: 137, name: "Command Block", mcId: "minecraft:command_block" },
  { id: 138, name: "Beacon", mcId: "minecraft:beacon" },
  { id: 139, name: "Cobblestone Wall", mcId: "minecraft:cobblestone_wall" },
  { id: "139:1", name: "Mossy Cobblestone Wall", mcId: "minecraft:cobblestone_wall" },
  { id: 140, name: "Flower Pot", mcId: "minecraft:flower_pot" },
  { id: 141, name: "Carrots", mcId: "minecraft:carrots" },
  { id: 142, name: "Potatoes", mcId: "minecraft:potatoes" },
  { id: 143, name: "Wooden Button", mcId: "minecraft:wooden_button" },
  { id: 144, name: "Mob Head", mcId: "minecraft:skull" },
  { id: 145, name: "Anvil", mcId: "minecraft:anvil" },
  { id: 146, name: "Trapped Chest", mcId: "minecraft:trapped_chest" },
  { id: 147, name: "Weighted Pressure Plate", mcId: "light) (minecraft:light_weighted_pressure_plate" },
  { id: 148, name: "Weighted Pressure Plate", mcId: "heavy) (minecraft:heavy_weighted_pressure_plate" },
  { id: 149, name: "Redstone Comparator", mcId: "inactive) (minecraft:unpowered_comparator" },
  { id: 150, name: "Redstone Comparator", mcId: "active) (minecraft:powered_comparator" },
  { id: 151, name: "Daylight Sensor", mcId: "minecraft:daylight_detector" },
  { id: 152, name: "Redstone Block", mcId: "minecraft:redstone_block" },
  { id: 153, name: "Nether Quartz Ore", mcId: "minecraft:quartz_ore" },
  { id: 154, name: "Hopper", mcId: "minecraft:hopper" },
  { id: 155, name: "Quartz Block", mcId: "minecraft:quartz_block" },
  { id: "155:1", name: "Chiseled Quartz Block", mcId: "minecraft:quartz_block" },
  { id: "155:2", name: "Pillar Quartz Block", mcId: "minecraft:quartz_block" },
  { id: 156, name: "Quartz Stairs", mcId: "minecraft:quartz_stairs" },
  { id: 157, name: "Activator Rail", mcId: "minecraft:activator_rail" },
  { id: 158, name: "Dropper", mcId: "minecraft:dropper" },
  { id: 159, name: "White Stained Clay", mcId: "minecraft:stained_hardened_clay" },
  { id: "159:1", name: "Orange Stained Clay", mcId: "minecraft:stained_hardened_clay" },
  { id: "159:2", name: "Magenta Stained Clay", mcId: "minecraft:stained_hardened_clay" },
  { id: "159:3", name: "Light Blue Stained Clay", mcId: "minecraft:stained_hardened_clay" },
  { id: "159:4", name: "Yellow Stained Clay", mcId: "minecraft:stained_hardened_clay" },
  { id: "159:5", name: "Lime Stained Clay", mcId: "minecraft:stained_hardened_clay" },
  { id: "159:6", name: "Pink Stained Clay", mcId: "minecraft:stained_hardened_clay" },
  { id: "159:7", name: "Gray Stained Clay", mcId: "minecraft:stained_hardened_clay" },
  { id: "159:8", name: "Light Gray Stained Clay", mcId: "minecraft:stained_hardened_clay" },
  { id: "159:9", name: "Cyan Stained Clay", mcId: "minecraft:stained_hardened_clay" },
  { id: "159:10", name: "Purple Stained Clay", mcId: "minecraft:stained_hardened_clay" },
  { id: "159:11", name: "Blue Stained Clay", mcId: "minecraft:stained_hardened_clay" },
  { id: "159:12", name: "Brown Stained Clay", mcId: "minecraft:stained_hardened_clay" },
  { id: "159:13", name: "Green Stained Clay", mcId: "minecraft:stained_hardened_clay" },
  { id: "159:14", name: "Red Stained Clay", mcId: "minecraft:stained_hardened_clay" },
  { id: "159:15", name: "Black Stained Clay", mcId: "minecraft:stained_hardened_clay" },
  { id: 160, name: "White Stained Glass Pane", mcId: "minecraft:stained_glass_pane" },
  { id: "160:1", name: "Orange Stained Glass Pane", mcId: "minecraft:stained_glass_pane" },
  { id: "160:2", name: "Magenta Stained Glass Pane", mcId: "minecraft:stained_glass_pane" },
  { id: "160:3", name: "Light Blue Stained Glass Pane", mcId: "minecraft:stained_glass_pane" },
  { id: "160:4", name: "Yellow Stained Glass Pane", mcId: "minecraft:stained_glass_pane" },
  { id: "160:5", name: "Lime Stained Glass Pane", mcId: "minecraft:stained_glass_pane" },
  { id: "160:6", name: "Pink Stained Glass Pane", mcId: "minecraft:stained_glass_pane" },
  { id: "160:7", name: "Gray Stained Glass Pane", mcId: "minecraft:stained_glass_pane" },
  { id: "160:8", name: "Light Gray Stained Glass Pane", mcId: "minecraft:stained_glass_pane" },
  { id: "160:9", name: "Cyan Stained Glass Pane", mcId: "minecraft:stained_glass_pane" },
  { id: "160:10", name: "Purple Stained Glass Pane", mcId: "minecraft:stained_glass_pane" },
  { id: "160:11", name: "Blue Stained Glass Pane", mcId: "minecraft:stained_glass_pane" },
  { id: "160:12", name: "Brown Stained Glass Pane", mcId: "minecraft:stained_glass_pane" },
  { id: "160:13", name: "Green Stained Glass Pane", mcId: "minecraft:stained_glass_pane" },
  { id: "160:14", name: "Red Stained Glass Pane", mcId: "minecraft:stained_glass_pane" },
  { id: "160:15", name: "Black Stained Glass Pane", mcId: "minecraft:stained_glass_pane" },
  { id: 161, name: "Acacia Leaves", mcId: "minecraft:leaves2" },
  { id: "161:1", name: "Dark Oak Leaves", mcId: "minecraft:leaves2" },
  { id: 162, name: "Acacia Wood", mcId: "minecraft:logs2" },
  { id: "162:1", name: "Dark Oak Wood", mcId: "minecraft:logs2" },
  { id: 163, name: "Acacia Wood Stairs", mcId: "minecraft:acacia_stairs" },
  { id: 164, name: "Dark Oak Wood Stairs", mcId: "minecraft:dark_oak_stairs" },
  { id: 165, name: "Slime Block", mcId: "minecraft:slime" },
  { id: 166, name: "Barrier", mcId: "minecraft:barrier" },
  { id: 167, name: "Iron Trapdoor", mcId: "minecraft:iron_trapdoor" },
  { id: 168, name: "Prismarine", mcId: "minecraft:prismarine" },
  { id: "168:1", name: "Prismarine Bricks", mcId: "minecraft:prismarine" },
  { id: "168:2", name: "Dark Prismarine", mcId: "minecraft:prismarine" },
  { id: 169, name: "Sea Lantern", mcId: "minecraft:sea_lantern" },
  { id: 170, name: "Hay Bale", mcId: "minecraft:hay_block" },
  { id: 171, name: "White Carpet", mcId: "minecraft:carpet" },
  { id: "171:1", name: "Orange Carpet", mcId: "minecraft:carpet" },
  { id: "171:2", name: "Magenta Carpet", mcId: "minecraft:carpet" },
  { id: "171:3", name: "Light Blue Carpet", mcId: "minecraft:carpet" },
  { id: "171:4", name: "Yellow Carpet", mcId: "minecraft:carpet" },
  { id: "171:5", name: "Lime Carpet", mcId: "minecraft:carpet" },
  { id: "171:6", name: "Pink Carpet", mcId: "minecraft:carpet" },
  { id: "171:7", name: "Gray Carpet", mcId: "minecraft:carpet" },
  { id: "171:8", name: "Light Gray Carpet", mcId: "minecraft:carpet" },
  { id: "171:9", name: "Cyan Carpet", mcId: "minecraft:carpet" },
  { id: "171:10", name: "Purple Carpet", mcId: "minecraft:carpet" },
  { id: "171:11", name: "Blue Carpet", mcId: "minecraft:carpet" },
  { id: "171:12", name: "Brown Carpet", mcId: "minecraft:carpet" },
  { id: "171:13", name: "Green Carpet", mcId: "minecraft:carpet" },
  { id: "171:14", name: "Red Carpet", mcId: "minecraft:carpet" },
  { id: "171:15", name: "Black Carpet", mcId: "minecraft:carpet" },
  { id: 172, name: "Hardened Clay", mcId: "minecraft:hardened_clay" },
  { id: 173, name: "Block of Coal", mcId: "minecraft:coal_block" },
  { id: 174, name: "Packed Ice", mcId: "minecraft:packed_ice" },
  { id: 175, name: "Sunflower", mcId: "minecraft:double_plant" },
  { id: "175:1", name: "Lilac", mcId: "minecraft:double_plant" },
  { id: "175:2", name: "Double Tallgrass", mcId: "minecraft:double_plant" },
  { id: "175:3", name: "Large Fern", mcId: "minecraft:double_plant" },
  { id: "175:4", name: "Rose Bush", mcId: "minecraft:double_plant" },
  { id: "175:5", name: "Peony", mcId: "minecraft:double_plant" },
  { id: 176, name: "Free-standing Banner", mcId: "minecraft:standing_banner" },
  { id: 177, name: "Wall-mounted Banner", mcId: "minecraft:wall_banner" },
  { id: 178, name: "Inverted Daylight Sensor", mcId: "minecraft:daylight_detector_inverted" },
  { id: 179, name: "Red Sandstone", mcId: "minecraft:red_sandstone" },
  { id: "179:1", name: "Smooth Red Sandstone", mcId: "minecraft:red_sandstone" },
  { id: "179:2", name: "Chiseled Red Sandstone", mcId: "minecraft:red_sandstone" },
  { id: 180, name: "Red Sandstone Stairs", mcId: "minecraft:red_sandstone_stairs" },
  { id: 181, name: "Double Red Sandstone Slab", mcId: "minecraft:stone_slab2" },
  { id: 182, name: "Red Sandstone Slab", mcId: "minecraft:double_stone_slab2" },
  { id: 183, name: "Spruce Fence Gate", mcId: "minecraft:spruce_fence_gate" },
  { id: 184, name: "Birch Fence Gate", mcId: "minecraft:birch_fence_gate" },
  { id: 185, name: "Jungle Fence Gate", mcId: "minecraft:jungle_fence_gate" },
  { id: 186, name: "Dark Oak Fence Gate", mcId: "minecraft:dark_oak_fence_gate" },
  { id: 187, name: "Acacia Fence Gate", mcId: "minecraft:acacia_fence_gate" },
  { id: 188, name: "Spruce Fence", mcId: "minecraft:spruce_fence" },
  { id: 189, name: "Birch Fence", mcId: "minecraft:birch_fence" },
  { id: 190, name: "Jungle Fence", mcId: "minecraft:jungle_fence" },
  { id: 191, name: "Dark Oak Fence", mcId: "minecraft:dark_oak_fence" },
  { id: 192, name: "Acacia Fence", mcId: "minecraft:acacia_fence" },
  { id: 193, name: "Spure Door Block", mcId: "minecraft:spruce_door" },
  { id: 194, name: "Birch Door Block", mcId: "minecraft:birch_door" },
  { id: 195, name: "Jungle Door Block", mcId: "minecraft:jungle_door" },
  { id: 196, name: "Acacia Door Block", mcId: "minecraft:acacia_door" },
  { id: 197, name: "Dark Oak Door Block", mcId: "minecraft:dark_oak_door" },
  { id: 256, name: "Iron Shovel", mcId: "minecraft:iron_shovel" },
  { id: 257, name: "Iron Pickaxe", mcId: "minecraft:iron_pickaxe" },
  { id: 258, name: "Iron Axe", mcId: "minecraft:iron_axe" },
  { id: 259, name: "Flint and Steel", mcId: "minecraft:flint_and_steel" },
  { id: 260, name: "Apple", mcId: "minecraft:apple" },
  { id: 261, name: "Bow", mcId: "minecraft:bow" },
  { id: 262, name: "Arrow", mcId: "minecraft:arrow" },
  { id: 263, name: "Coal", mcId: "minecraft:coal" },
  { id: "263:1", name: "Charcoal", mcId: "minecraft:coal" },
  { id: 264, name: "Diamond", mcId: "minecraft:diamond" },
  { id: 265, name: "Iron Ingot", mcId: "minecraft:iron_ingot" },
  { id: 266, name: "Gold Ingot", mcId: "minecraft:gold_ingot" },
  { id: 267, name: "Iron Sword", mcId: "minecraft:iron_sword" },
  { id: 268, name: "Wooden Sword", mcId: "minecraft:wooden_sword" },
  { id: 269, name: "Wooden Shovel", mcId: "minecraft:wooden_shovel" },
  { id: 270, name: "Wooden Pickaxe", mcId: "minecraft:wooden_pickaxe" },
  { id: 271, name: "Wooden Axe", mcId: "minecraft:wooden_axe" },
  { id: 272, name: "Stone Sword", mcId: "minecraft:stone_sword" },
  { id: 273, name: "Stone Shovel", mcId: "minecraft:stone_shovel" },
  { id: 274, name: "Stone Pickaxe", mcId: "minecraft:stone_pickaxe" },
  { id: 275, name: "Stone Axe", mcId: "minecraft:stone_axe" },
  { id: 276, name: "Diamond Sword", mcId: "minecraft:diamond_sword" },
  { id: 277, name: "Diamond Shovel", mcId: "minecraft:diamond_shovel" },
  { id: 278, name: "Diamond Pickaxe", mcId: "minecraft:diamond_pickaxe" },
  { id: 279, name: "Diamond Axe", mcId: "minecraft:diamond_axe" },
  { id: 280, name: "Stick", mcId: "minecraft:stick" },
  { id: 281, name: "Bowl", mcId: "minecraft:bowl" },
  { id: 282, name: "Mushroom Stew", mcId: "minecraft:mushroom_stew" },
  { id: 283, name: "Golden Sword", mcId: "minecraft:golden_sword" },
  { id: 284, name: "Golden Shovel", mcId: "minecraft:golden_shovel" },
  { id: 285, name: "Golden Pickaxe", mcId: "minecraft:golden_pickaxe" },
  { id: 286, name: "Golden Axe", mcId: "minecraft:golden_axe" },
  { id: 287, name: "String", mcId: "minecraft:string" },
  { id: 288, name: "Feather", mcId: "minecraft:feather" },
  { id: 289, name: "Gunpowder", mcId: "minecraft:gunpowder" },
  { id: 290, name: "Wooden Hoe", mcId: "minecraft:wooden_hoe" },
  { id: 291, name: "Stone Hoe", mcId: "minecraft:stone_hoe" },
  { id: 292, name: "Iron Hoe", mcId: "minecraft:iron_hoe" },
  { id: 293, name: "Diamond Hoe", mcId: "minecraft:diamond_hoe" },
  { id: 294, name: "Golden Hoe", mcId: "minecraft:golden_hoe" },
  { id: 295, name: "Wheat Seeds", mcId: "minecraft:wheat_seeds" },
  { id: 296, name: "Wheat", mcId: "minecraft:wheat" },
  { id: 297, name: "Bread", mcId: "minecraft:bread" },
  { id: 298, name: "Leather Helmet", mcId: "minecraft:leather_helmet" },
  { id: 299, name: "Leather Tunic", mcId: "minecraft:leather_chestplate" },
  { id: 300, name: "Leather Pants", mcId: "minecraft:leather_leggings" },
  { id: 301, name: "Leather Boots", mcId: "minecraft:leather_boots" },
  { id: 302, name: "Chainmail Helmet", mcId: "minecraft:chainmail_helmet" },
  { id: 303, name: "Chainmail Chestplate", mcId: "minecraft:chainmail_chestplate" },
  { id: 304, name: "Chainmail Leggings", mcId: "minecraft:chainmail_leggings" },
  { id: 305, name: "Chainmail Boots", mcId: "minecraft:chainmail_boots" },
  { id: 306, name: "Iron Helmet", mcId: "minecraft:iron_helmet" },
  { id: 307, name: "Iron Chestplate", mcId: "minecraft:iron_chestplate" },
  { id: 308, name: "Iron Leggings", mcId: "minecraft:iron_leggings" },
  { id: 309, name: "Iron Boots", mcId: "minecraft:iron_boots" },
  { id: 310, name: "Diamond Helmet", mcId: "minecraft:diamond_helmet" },
  { id: 311, name: "Diamond Chestplate", mcId: "minecraft:diamond_chestplate" },
  { id: 312, name: "Diamond Leggings", mcId: "minecraft:diamond_leggings" },
  { id: 313, name: "Diamond Boots", mcId: "minecraft:diamond_boots" },
  { id: 314, name: "Golden Helmet", mcId: "minecraft:golden_helmet" },
  { id: 315, name: "Golden Chestplate", mcId: "minecraft:golden_chestplate" },
  { id: 316, name: "Golden Leggings", mcId: "minecraft:golden_leggings" },
  { id: 317, name: "Golden Boots", mcId: "minecraft:golden_boots" },
  { id: 318, name: "Flint", mcId: "minecraft:flint_and_steel" },
  { id: 319, name: "Raw Porkchop", mcId: "minecraft:porkchop" },
  { id: 320, name: "Cooked Porkchop", mcId: "minecraft:cooked_porkchop" },
  { id: 321, name: "Painting", mcId: "minecraft:painting" },
  { id: 322, name: "Golden Apple", mcId: "minecraft:golden_apple" },
  { id: "322:1", name: "Enchanted Golden Apple", mcId: "minecraft:golden_apple" },
  { id: 323, name: "Sign", mcId: "minecraft:sign" },
  { id: 324, name: "Wooden Door", mcId: "minecraft:wooden_door" },
  { id: 325, name: "Bucket", mcId: "minecraft:bucket" },
  { id: 326, name: "Water Bucket", mcId: "minecraft:water_bucket" },
  { id: 327, name: "Lava Bucket", mcId: "minecraft:lava_bucket" },
  { id: 328, name: "Minecart", mcId: "minecraft:minecart" },
  { id: 329, name: "Saddle", mcId: "minecraft:saddle" },
  { id: 330, name: "Iron Door", mcId: "minecraft:iron_door" },
  { id: 331, name: "Redstone", mcId: "minecraft:redstone" },
  { id: 332, name: "Snowball", mcId: "minecraft:snowball" },
  { id: 333, name: "Boat", mcId: "minecraft:boat" },
  { id: 334, name: "Leather", mcId: "minecraft:leather" },
  { id: 335, name: "Milk Bucket", mcId: "minecraft:milk_bucket" },
  { id: 336, name: "Brick", mcId: "minecraft:brick" },
  { id: 337, name: "Clay", mcId: "minecraft:clay_ball" },
  { id: 338, name: "Sugar Canes", mcId: "minecraft:reeds" },
  { id: 339, name: "Paper", mcId: "minecraft:paper" },
  { id: 340, name: "Book", mcId: "minecraft:book" },
  { id: 341, name: "Slimeball", mcId: "minecraft:slime_ball" },
  { id: 342, name: "Minecart with Chest", mcId: "minecraft:chest_minecart" },
  { id: 343, name: "Minecart with Furnace", mcId: "minecraft:furnace_minecart" },
  { id: 344, name: "Egg", mcId: "minecraft:egg" },
  { id: 345, name: "Compass", mcId: "minecraft:compass" },
  { id: 346, name: "Fishing Rod", mcId: "minecraft:fishing_rod" },
  { id: 347, name: "Clock", mcId: "minecraft:clock" },
  { id: 348, name: "Glowstone Dust", mcId: "minecraft:glowstone_dust" },
  { id: 349, name: "Raw Fish", mcId: "minecraft:fish" },
  { id: "349:1", name: "Raw Salmon", mcId: "minecraft:fish" },
  { id: "349:2", name: "Clownfish", mcId: "minecraft:fish" },
  { id: "349:3", name: "Pufferfish", mcId: "minecraft:fish" },
  { id: 350, name: "Cooked Fish", mcId: "minecraft:cooked_fish" },
  { id: "350:1", name: "Cooked Salmon", mcId: "minecraft:cooked_fish" },
  { id: 351, name: "Ink Sack", mcId: "minecraft:dye" },
  { id: "351:1", name: "Rose Red", mcId: "minecraft:dye" },
  { id: "351:2", name: "Cactus Green", mcId: "minecraft:dye" },
  { id: "351:3", name: "Coco Beans", mcId: "minecraft:dye" },
  { id: "351:4", name: "Lapis Lazuli", mcId: "minecraft:dye" },
  { id: "351:5", name: "Purple Dye", mcId: "minecraft:dye" },
  { id: "351:6", name: "Cyan Dye", mcId: "minecraft:dye" },
  { id: "351:7", name: "Light Gray Dye", mcId: "minecraft:dye" },
  { id: "351:8", name: "Gray Dye", mcId: "minecraft:dye" },
  { id: "351:9", name: "Pink Dye", mcId: "minecraft:dye" },
  { id: "351:10", name: "Lime Dye", mcId: "minecraft:dye" },
  { id: "351:11", name: "Dandelion Yellow", mcId: "minecraft:dye" },
  { id: "351:12", name: "Light Blue Dye", mcId: "minecraft:dye" },
  { id: "351:13", name: "Magenta Dye", mcId: "minecraft:dye" },
  { id: "351:14", name: "Orange Dye", mcId: "minecraft:dye" },
  { id: "351:15", name: "Bone Meal", mcId: "minecraft:dye" },
  { id: 352, name: "Bone", mcId: "minecraft:bone" },
  { id: 353, name: "Sugar", mcId: "minecraft:sugar" },
  { id: 354, name: "Cake", mcId: "minecraft:cake" },
  { id: 355, name: "Bed", mcId: "minecraft:bed" },
  { id: 356, name: "Redstone Repeater", mcId: "minecraft:repeater" },
  { id: 357, name: "Cookie", mcId: "minecraft:cookie" },
  { id: 358, name: "Map", mcId: "minecraft:filled_map" },
  { id: 359, name: "Shears", mcId: "minecraft:shears" },
  { id: 360, name: "Melon", mcId: "minecraft:melon" },
  { id: 361, name: "Pumpkin Seeds", mcId: "minecraft:pumpkin_seeds" },
  { id: 362, name: "Melon Seeds", mcId: "minecraft:melon_seeds" },
  { id: 363, name: "Raw Beef", mcId: "minecraft:beef" },
  { id: 364, name: "Steak", mcId: "minecraft:cooked_beef" },
  { id: 365, name: "Raw Chicken", mcId: "minecraft:chicken" },
  { id: 366, name: "Cooked Chicken", mcId: "minecraft:cooked_chicken" },
  { id: 367, name: "Rotten Flesh", mcId: "minecraft:rotten_flesh" },
  { id: 368, name: "Ender Pearl", mcId: "minecraft:ender_pearl" },
  { id: 369, name: "Blaze Rod", mcId: "minecraft:blaze_rod" },
  { id: 370, name: "Ghast Tear", mcId: "minecraft:ghast_tear" },
  { id: 371, name: "Gold Nugget", mcId: "minecraft:gold_nugget" },
  { id: 372, name: "Nether Wart", mcId: "minecraft:nether_wart" },
  { id: 373, name: "Potion", mcId: "minecraft:potion" },
  { id: 374, name: "Glass Bottle", mcId: "minecraft:glass_bottle" },
  { id: 375, name: "Spider Eye", mcId: "minecraft:spider_eye" },
  { id: 376, name: "Fermented Spider Eye", mcId: "minecraft:fermented_spider_eye" },
  { id: 377, name: "Blaze Powder", mcId: "minecraft:blaze_powder" },
  { id: 378, name: "Magma Cream", mcId: "minecraft:magma_cream" },
  { id: 379, name: "Brewing Stand", mcId: "minecraft:brewing_stand" },
  { id: 380, name: "Cauldron", mcId: "minecraft:cauldron" },
  { id: 381, name: "Eye of Ender", mcId: "minecraft:ender_eye" },
  { id: 382, name: "Glistering Melon", mcId: "minecraft:speckled_melon" },
  { id: "383:50", name: "Spawn Creeper", mcId: "minecraft:spawn_egg" },
  { id: "383:51", name: "Spawn Skeleton", mcId: "minecraft:spawn_egg" },
  { id: "383:52", name: "Spawn Spider", mcId: "minecraft:spawn_egg" },
  { id: "383:54", name: "Spawn Zombie", mcId: "minecraft:spawn_egg" },
  { id: "383:55", name: "Spawn Slime", mcId: "minecraft:spawn_egg" },
  { id: "383:56", name: "Spawn Ghast", mcId: "minecraft:spawn_egg" },
  { id: "383:57", name: "Spawn Pigman", mcId: "minecraft:spawn_egg" },
  { id: "383:58", name: "Spawn Enderman", mcId: "minecraft:spawn_egg" },
  { id: "383:59", name: "Spawn Cave Spider", mcId: "minecraft:spawn_egg" },
  { id: "383:60", name: "Spawn Silverfish", mcId: "minecraft:spawn_egg" },
  { id: "383:61", name: "Spawn Blaze", mcId: "minecraft:spawn_egg" },
  { id: "383:62", name: "Spawn Magma Cube", mcId: "minecraft:spawn_egg" },
  { id: "383:65", name: "Spawn Bat", mcId: "minecraft:spawn_egg" },
  { id: "383:66", name: "Spawn Witch", mcId: "minecraft:spawn_egg" },
  { id: "383:67", name: "Spawn Endermite", mcId: "minecraft:spawn_egg" },
  { id: "383:68", name: "Spawn Guardian", mcId: "minecraft:spawn_egg" },
  { id: "383:90", name: "Spawn Pig", mcId: "minecraft:spawn_egg" },
  { id: "383:91", name: "Spawn Sheep", mcId: "minecraft:spawn_egg" },
  { id: "383:92", name: "Spawn Cow", mcId: "minecraft:spawn_egg" },
  { id: "383:93", name: "Spawn Chicken", mcId: "minecraft:spawn_egg" },
  { id: "383:94", name: "Spawn Squid", mcId: "minecraft:spawn_egg" },
  { id: "383:95", name: "Spawn Wolf", mcId: "minecraft:spawn_egg" },
  { id: "383:96", name: "Spawn Mooshroom", mcId: "minecraft:spawn_egg" },
  { id: "383:98", name: "Spawn Ocelot", mcId: "minecraft:spawn_egg" },
  { id: "383:100", name: "Spawn Horse", mcId: "minecraft:spawn_egg" },
  { id: "383:101", name: "Spawn Rabbit", mcId: "minecraft:spawn_egg" },
  { id: "383:120", name: "Spawn Villager", mcId: "minecraft:spawn_egg" },
  { id: 384, name: "Bottle o’ Enchanting", mcId: "minecraft:experience_bottle" },
  { id: 385, name: "Fire Charge", mcId: "minecraft:fire_charge" },
  { id: 386, name: "Book and Quill", mcId: "minecraft:writable_book" },
  { id: 387, name: "Written Book", mcId: "minecraft:written_book" },
  { id: 388, name: "Emerald", mcId: "minecraft:emerald" },
  { id: 389, name: "Item Frame", mcId: "minecraft:item_frame" },
  { id: 390, name: "Flower Pot", mcId: "minecraft:flower_pot" },
  { id: 391, name: "Carrot", mcId: "minecraft:carrot" },
  { id: 392, name: "Potato", mcId: "minecraft:potato" },
  { id: 393, name: "Baked Potato", mcId: "minecraft:baked_potato" },
  { id: 394, name: "Poisonous Potato", mcId: "minecraft:poisonous_potato" },
  { id: 395, name: "Empty Map", mcId: "minecraft:map" },
  { id: 396, name: "Golden Carrot", mcId: "minecraft:golden_carrot" },
  { id: 397, name: "Mob Head", mcId: "Skeleton) (minecraft:skull" },
  { id: "397:1", name: "Mob Head", mcId: "Wither Skeleton) (minecraft:skull" },
  { id: "397:2", name: "Mob Head", mcId: "Zombie) (minecraft:skull" },
  { id: "397:3", name: "Mob Head", mcId: "Human) (minecraft:skull" },
  { id: "397:4", name: "Mob Head", mcId: "Creeper) (minecraft:skull" },
  { id: 398, name: "Carrot on a Stick", mcId: "minecraft:carrot_on_a_stick" },
  { id: 399, name: "Nether Star", mcId: "minecraft:nether_star" },
  { id: 400, name: "Pumpkin Pie", mcId: "minecraft:pumpkin_pie" },
  { id: 401, name: "Firework Rocket", mcId: "minecraft:fireworks" },
  { id: 402, name: "Firework Star", mcId: "minecraft:firework_charge" },
  { id: 403, name: "Enchanted Book", mcId: "minecraft:enchanted_book" },
  { id: 404, name: "Redstone Comparator", mcId: "minecraft:comparator" },
  { id: 405, name: "Nether Brick", mcId: "minecraft:netherbrick" },
  { id: 406, name: "Nether Quartz", mcId: "minecraft:quartz" },
  { id: 407, name: "Minecart with TNT", mcId: "minecraft:tnt_minecart" },
  { id: 408, name: "Minecart with Hopper", mcId: "minecraft:hopper_minecart" },
  { id: 409, name: "Prismarine Shard", mcId: "minecraft:prismarine_shard" },
  { id: 410, name: "Prismarine Crystals", mcId: "minecraft:prismarine_crystals" },
  { id: 411, name: "Raw Rabbit", mcId: "minecraft:rabbit" },
  { id: 412, name: "Cooked Rabbit", mcId: "minecraft:cooked_rabbit" },
  { id: 413, name: "Rabbit Stew", mcId: "minecraft:rabbit_stew" },
  { id: 414, name: "Rabbit’s Foot", mcId: "minecraft:rabbit_foot" },
  { id: 415, name: "Rabbit Hide", mcId: "minecraft:rabbit_hide" },
  { id: 416, name: "Armor Stand", mcId: "minecraft:armor_stand" },
  { id: 417, name: "Iron Horse Armor", mcId: "minecraft:iron_horse_armor" },
  { id: 418, name: "Golden Horse Armor", mcId: "minecraft:golden_horse_armor" },
  { id: 419, name: "Diamond Horse Armor", mcId: "minecraft:diamond_horse_armor" },
  { id: 420, name: "Lead", mcId: "minecraft:lead" },
  { id: 421, name: "Name Tag", mcId: "minecraft:name_tag" },
  { id: 422, name: "Minecart with Command Block", mcId: "minecraft:command_block_minecart" },
  { id: 423, name: "Raw Mutton", mcId: "minecraft:mutton" },
  { id: 424, name: "Cooked Mutton", mcId: "minecraft:cooked_mutton" },
  { id: 425, name: "Banner", mcId: "minecraft:banner" },
  { id: 427, name: "Spruce Door", mcId: "minecraft:spruce_door" },
  { id: 428, name: "Birch Door", mcId: "minecraft:birch_door" },
  { id: 429, name: "Jungle Door", mcId: "minecraft:jungle_door" },
  { id: 430, name: "Acacia Door", mcId: "minecraft:acacia_door" },
  { id: 431, name: "Dark Oak Door", mcId: "minecraft:dark_oak_door" },
  { id: 2256, name: "13 Disc", mcId: "minecraft:record_13" },
  { id: 2257, name: "Cat Disc", mcId: "minecraft:record_cat" },
  { id: 2258, name: "Blocks Disc", mcId: "minecraft:record_blocks" },
  { id: 2259, name: "Chirp Disc", mcId: "minecraft:record_chirp" },
  { id: 2260, name: "Far Disc", mcId: "minecraft:record_far" },
  { id: 2261, name: "Mall Disc", mcId: "minecraft:record_mall" },
  { id: 2262, name: "Mellohi Disc", mcId: "minecraft:record_mellohi" },
  { id: 2263, name: "Stal Disc", mcId: "minecraft:record_stal" },
  { id: 2264, name: "Strad Disc", mcId: "minecraft:record_strad" },
  { id: 2265, name: "Ward Disc", mcId: "minecraft:record_ward" },
  { id: 2266, name: "11 Disc", mcId: "minecraft:record_11" },
  { id: 2267, name: "Wait Disc", mcId: "minecraft:record_wait" }
];

export default MINECRAFT_ITEMS;
